/**
 * @author: Steffen Beck
 * @snr: s211091
 */

package Gui.Buttons;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;

import Sudoku.Main;

public class Hint extends JButton {
	
	private static final long serialVersionUID = 8063731769097333941L; //Auto-generated by Eclipse

	/**
	 * Constructor for the extended button class.
	 * 
	 * @param title The title on the button.
	 */
	public Hint(String title) {
		this.setText(title);
		
		this.addActionListener(new ActionListener() {
		    @Override
		    public void actionPerformed(ActionEvent e) {
		    	if (Main.currentGame == null) return; //No game registered
		    	if (!Main.currentGame.active) return; //Game registered but not active.. Completed?
		    	
		    	Main.currentGame.hint();
		    }
		});
	}
	
	
}
