/**
 * @author: Steffen Beck
 * @snr: s211091
 */

package Gui.Buttons;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;

import Constants.Language;
import Constants.Settings;
import Sudoku.Game;
import Sudoku.Main;

public class New extends JButton {
	
	private static final long serialVersionUID = -663943991956308507L; //Auto-generated by Eclipse

	/**
	 * Constructor for the extended button class.
	 * 
	 * @param title The title on the button.
	 */
	public New(String title) {
		this.setText(title);
		
		this.addActionListener(new ActionListener() {
		    @Override
		    public void actionPerformed(ActionEvent e) {
		        
		    	try {
		    		Main.plate.clear();
		    		
		    		Game sudoku = new Game(Settings.EMPTY_GRID, true);
		    		
		    		Main.currentGame = sudoku;
		    		
		    		//Print game to console
		    		//System.out.print(Main.currentGame);
		    		
		    		Gui.Panels.Window.labelMessage.setText(Language.LANG_STATUS_GAME_STARTED);
		    		
		    	} catch (Exception se) {
		    		System.out.println(se.getMessage());
		    	}
		    }
		});
	}
}
